### ISSUE TITLE
crash when writing to parameters with single digit BusAddress

### ISSUE THREAD

**Issue by parhelion22** [zivillian/ism7mqtt#10]
Thank you very much for your work!

I try to write to the parameter 18131 "Kesselübertemperatur bei Speicherladung" of my CGB-2 (device id 18000). However, values do not appear to be written, if the umlauts in the parameter name are kept (i.e. when using Wolf/192.168.178.40/CGB-2_0x8/set {"Kesselübertemperatur bei Speicherladung":15}). If the umlauts are replaced (i.e. when using {"Kesseluebertemperatur bei Speicherladung":15}), then ism7mqtt terminates, but nonetheless the new value is written to the CGB-2 (value change visible after restarting ism7mqtt). Am I doing something wrong?

[smartsetpc.sdf.zip](https://github.com/zivillian/ism7mqtt/files/7978825/smartsetpc.sdf.zip)
[Dump.txt](https://github.com/zivillian/ism7mqtt/files/7978831/Dump.txt)

**Comment by parhelion22** [comment]
Further testing showed that the problem is not limited to parameters with umlauts. ism7mqtt terminates (but writes the values before) whenever I try to write to the CGB-2 (e.g. also when using Wolf/192.168.178.40/CGB-2_0x8/set {"Hysterese Sammler":5}).

In contrast, writing to the BM-2 does not terminate ism7mqtt (e.g. Wolf/192.168.178.40/BM-2_0x35/set {"Warmwassersolltemperatur eingestellt":55}).

**Comment by zivillian** [comment]
I can reproduce the Problem with my CGB-2 - I'll look into this

**Comment by zivillian** [comment]
The reason is, that the BusAddress (`ba`) differs between the request (`0x03`) and response (`0x3`). They are currently interpreted as string, so I have to switch to parsing the hex addresses.

I've also seen, that your debug log contains some helpful UnicodeTextConverter Output, so I will add an initial implementation to support your "Heizkreis".

**Comment by zivillian** [comment]
Can you test the version from https://github.com/zivillian/ism7mqtt/actions/runs/1786325237? It does work for me, and I will merge the PR if it also works for you.

**Comment by zivillian** [comment]
I've added the initial support for UnicodeTextConverter - can you test the version from https://github.com/zivillian/ism7mqtt/actions/runs/1786642844 and verify that there is a new Attribute `Heizkreis Benamung` with the value `Heizkreis`?

**Comment by parhelion22** [comment]
> Can you test the version from https://github.com/zivillian/ism7mqtt/actions/runs/1786325237? It does work for me, and I will merge the PR if it also works for you.

Thank you very much, writing to the CGB-2 now works perfectly.

**Comment by parhelion22** [comment]
> I've added the initial support for UnicodeTextConverter - can you test the version from https://github.com/zivillian/ism7mqtt/actions/runs/1786642844 and verify that there is a new Attribute `Heizkreis Benamung` with the value `Heizkreis`?

Unfortunetely, the parameter "Heizkreis Benamung" (parameter id 34043) of my device "DHK_BM-2" (device id 34000) does not show up. Writing blindly to it (by using Wolf/192.168.178.40/BM-2_0x35/set {"Heizkreis Benamung":"Test"}) seems to have no effect either.
[Dump.txt](https://github.com/zivillian/ism7mqtt/files/7992096/Dump.txt)

**Comment by parhelion22** [comment]
Further testing showed that in the version https://github.com/zivillian/ism7mqtt/actions/runs/1786642844, parameters that could be read and written before can no longer be read and written. This includes (among others) "Programmwahl_35013", "Programmwahl_34030", "Vorlauftemperatur Heizkurve", "Normaussentemperatur Heizkurve", "Sockeltemperatur Heizkurve" and "Startpunkt Heizkurve". With the version https://github.com/zivillian/ism7mqtt/actions/runs/1786325237 mentioned before, this problem does not exist.

[Dump.txt](https://github.com/zivillian/ism7mqtt/files/8000474/Dump.txt)

**Comment by zivillian** [comment]
can you send me your `parameter.json`?

**Comment by zivillian** [comment]
can you test again with the binaries from https://github.com/zivillian/ism7mqtt/actions/runs/1802957931? This version separates virtual devices on the same busaddress with their own device template. In your case there will be two new device (`DHK_BM-2` and `WWSystem_BM-2`) and the corresponding parameters will be moved to those devices.

**Comment by parhelion22** [comment]
Thank you very much for looking into this. Reading and writing now works perfectly. Even the parameter "Heizkreis Benamung" now shows up (but cannot be written to).

See my parameters.json attached.

[parameter.json.zip](https://github.com/zivillian/ism7mqtt/files/8015149/parameter.json.zip)
