### ISSUE TITLE
ism7mqtt -i does not accept hostname

### ISSUE THREAD

**Issue by m6w6** [zivillian/ism7mqtt#100]
`ism7mqtt`'s `-i` option does not accept a hostname, despite advertising it in the command help.

**Comment by zivillian** [comment]
You are right - thanks for reporting. This was not intended.

Do you have a usecase for a hostname? (Should I update the help or add support for a hostname?)

**Comment by m6w6** [comment]
I usually use hostnames in my network, so support for them would be definitely preferred, but I understand that this would *be just nice* and maybe not worth the hassle.  

Thank you for your work on `ism7mqtt`!
