### ISSUE TITLE
Had to downgrade from 0.16 to 0.15

### ISSUE THREAD

**Issue by m6w6** [zivillian/ism7mqtt#103]
Not sure yet what happened, but I had to donwgrade from .16 to .15

The topic tree in MQTT looks the same at a first glance, but Homeassistant stopped updating with the new version and immediately resumed after downgrading to .15

<img width="369" alt="Screenshot 2024-03-24 at 22 07 38" src="https://github.com/zivillian/ism7mqtt/assets/1265282/fd1d18aa-a867-48eb-84bd-b57a27dabe65">

<img width="661" alt="Screenshot 2024-03-24 at 22 25 53" src="https://github.com/zivillian/ism7mqtt/assets/1265282/7b906d64-781c-43e4-8a7c-6ec9ab13e542">

<img width="653" alt="Screenshot 2024-03-24 at 22 29 54" src="https://github.com/zivillian/ism7mqtt/assets/1265282/7c0decb8-af4c-4fb5-9628-4d0b5d8ccb8a">

**Comment by zivillian** [comment]
@b3nn0 fyi

**Comment by b3nn0** [comment]
Hard to say much without any proper information.. logging of the addon? Discovery topics? Tried a restart of HA or the addon?
0.0.16 works just fine for me...

**Comment by zivillian** [comment]
@b3nn0 good to hear, that at least 50% of the installation are ok ;-)

@m6w6 can you show the full MQTT Tree, the corresponding part of the homeassistant autodiscovery tree and share the logs?

**Comment by zivillian** [comment]
after looking closely at the mqtt explorer screenshot, it seem, that there is JSON published:
![grafik](https://github.com/zivillian/ism7mqtt/assets/6039253/ff562bf0-2019-4c76-a72f-911da7938434)

v0.0.16 changed the handling of the home assistant discovery id in 57082dc (#101)

@m6w6 are you running a standalone ism7mqtt, the ism7mqtt docker image or the HA Addon?

**Comment by m6w6** [comment]
They definitely look different:

<img width="1121" alt="Screenshot 2024-03-25 at 12 27 52" src="https://github.com/zivillian/ism7mqtt/assets/1265282/3742260a-3b75-4872-ae03-381afe5c9bf0">

<img width="1116" alt="Screenshot 2024-03-25 at 12 34 14" src="https://github.com/zivillian/ism7mqtt/assets/1265282/3140b295-28d1-4e3c-8b96-3535aa3836cb">

**Comment by alexkno79** [comment]
Reading container I assume it‘s docker based. So you may pass either the HASS-ID or set the separate + retain environment variables

**Comment by zivillian** [comment]
The environment variable `ISM7_HOMEASSISTANT_ID` is initialized as an empty string in the ism7mqtt docker container. v0.0.16 changed the behaviour to ignore empty values for `ISM7_HOMEASSISTANT_ID` - so if you want separate topics you need to either set the environment variable `ISM7_HOMEASSISTANT_ID` to a non empty value or `ISM7_SEPARATE` (and maybe also `ISM7_RETAIN`) to `true`.

**Comment by m6w6** [comment]
After taking the last screenshots and looking at #101, I suspected it, but I just proved that -s|--separate fixes the issue for me.

I'm using command flags instead of env vars, though.

Thanks!
