### ISSUE TITLE
Parameter des zweiten Mischerkreises werden nicht angezeigt (WOLF Wärmepumpe CHA-10/400V mit BM-2 / homeassistant addon)

### ISSUE THREAD

**Issue by DieterChmod** [zivillian/ism7mqtt#109]
Die Entitäten meiner zwei Mischerkreise haben folgendes Namensschema:
Mischerkreis 1: sensor.wolf_mk_bm2\_**0x85**\_360011_vorlauftemperatur
Mischerkreis 2: sensor.wolf_mk_bm2\_**0x86**\_360011_vorlauftemperatur

Leider fehlen manche Parameter für den zweiten Mischerkreis, z.B. für select.wolf_mk_bm2_0x85_360051_programmwahl.

PS: Spitzenarbeit. Vielen Dank dafür !!!

**Comment by DieterChmod** [comment]
Hi,
ja, die Parameter sind sowohl im Wolf SmartSet Portal als auch in der App sichtbar. Siehe Screenshots:
![Wolf_App](https://github.com/zivillian/ism7mqtt/assets/45570637/d01c9938-a0e5-4ced-8481-53b2c79c5786)
![Wolf_SmartSet_Portal](https://github.com/zivillian/ism7mqtt/assets/45570637/279f6d45-7c06-419a-b83a-eb9f3c70a2cf)
Hier das parameter.json file:
[ism7-parameters-Wolf.json](https://github.com/user-attachments/files/15524983/ism7-parameters-Wolf.json)
Bezüglich des Debug Outputs: ICh weiß leider nicht, wie ich an die Informationen komme. Ich habe im Ism7MQTT addon den switch "Debug logging" aktiviert. Jetzt gibt es da den Protokoll-Output und die HA logs. Was benötigst Du genau, und wie komme ich an die Dateien?
Vielen Dank und Grüße

**Comment by DieterChmod** [comment]
HAllo, wollte kurz nachfragen, ob es zu diesem Thema Fortschritte gibt. Ich würde gerne helfen.

**Comment by zivillian** [comment]
ich brauche den Protokoll Output - also den Teil, der die XML Nachrichten enthält. Da steht unter anderem dann auch das Passwort drin, das soltlest du vorher entfernen.

**Comment by zivillian** [comment]
der Parameter `select.wolf_mk_bm2_0x85_360051_programmwahl` fehlt in deiner paramter.json - kannst du einmal versuchen die parameter.json neu zu erstellen? Wenn der Parameter dann immer noch fehlt, müsstest du das Log von der Erstellung hochladen.

**Comment by DieterChmod** [comment]
Gute Nachrichten, nach dem Update auf v0.0.17 und dem erneuten Erstellen der json Datei wird jetzt auch der Programmwahlparameter des zweiten Mischerkreises angezeigt. Problem gelöst.

**Comment by DieterChmod** [comment]
Das "issue" kann somit geschlossen werden.
