### ISSUE TITLE
Wert für Raumtemperatur(340000) schreiben

### ISSUE THREAD

**Issue by wrzlbrmft1** [zivillian/ism7mqtt#116]
Hallo,
ich würde ganz gerne den Wert für die Raumtemperatur setzen:
`["DHK_BM-2_0x35"].Raumtemperatur["340000"`

Im Log kommt folgendes:
`nothing to send for topic 'Wolf/xxx.xxx.xxx.xxx/DHK_BM-2_0x35' with payload '{"Raumtemperatur":{"340000":23}}'`

Gibt es eine Möglichkeit, in der Wolfsteuerung eine Raumtemperatur zu setzen?

**Comment by zivillian** [comment]
Kannst du deine `parameter.json` hochladen und den debug output nach einen neustart posten? Relevant wäre die `read-systemconfig-response`.

**Comment by wrzlbrmft1** [comment]
Danke für die Antwort:

Die parameter.json hätte ich hier:
[parameter.json](https://github.com/user-attachments/files/16698216/parameter.json)

Nur mit dem Debug-output innerhalb des Dockers hab ich meine Probleme. Kannst du mir einen Hinweis geben, wie ich an das Debug-log komme?

**Comment by zivillian** [comment]
für Docker kannst da

**Comment by zivillian** [comment]
ich hab mir das mit deiner parameter.json gerade mal anschaut und sehe, dass der Parameter Raumtemperatur readonly ist. Das ist also nicht die Solltemperatur, sondern die aktuelle Raumtemperatur.
