### ISSUE TITLE
IP wird in fhem mit hexadezimal übertragen

### ISSUE THREAD

**Issue by stephensworld** [zivillian/ism7mqtt#118]
Hallo,

ich habe dieses Tool mit meinem fhem verbunden. Werte werden übertragen, aber die IP sieht etwas seltsam aus.

`Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C:.* { json2nameValue($EVENT) }
Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C/Bypass_Status/value:.* value
Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C/Bypass_Status/text:.* text
Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C/Frost_Status/value:.* value
Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C/Frost_Status/text:.* text
Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C/Zuluftdruck:.* Zuluftdruck
Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C/Abluftdruck:.* Abluftdruck
Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C/Luftdurchsatz_Zuluft:.* Luftdurchsatz_Zuluft
Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C/Luftdurchsatz_Abluft:.* Luftdurchsatz_Abluft
Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C/Lueftungsstufe/value:.* value
Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C/Lueftungsstufe/text:.* text
Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C/Lueftungsstufe_als_Zahl_fuer_Slider:.* Lueftungsstufe_als_Zahl_fuer_Slider
Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C/Aussenlufttemperatur:.* Aussenlufttemperatur
Wolf_1921689917:Wolf/192\x2e168\x2e99\x2e17/CWL-2_0x3C/Vorheizregister/value:.* value `

Vielleicht liegt es auch an mqtt2 von fhem.

Vielen Dank 

Grüße 
Stephan

**Comment by zivillian** [comment]
das escaping kommt aus dem MQTT Modul in FHEM - da kann ich leider nichts machen.
