### ISSUE TITLE
Geräte / Entitäten werden in HA nicht erstellt / angezeigt

### ISSUE THREAD

**Issue by Sallion00** [zivillian/ism7mqtt#130]
Hallo,

ich hab ism7mqtt früher schon erfolgreich genutzt, bis vor ca. 9 Monaten die Verbindung nicht mehr zustande gekommen ist. Updates und co. haben damals nicht weiter geholfen und ich hab das Problem zur Seite gelegt. In HA hab ich die MQTT Geräte der Wolf Heizung durch die Weboberfläche gelöscht. Mit dem letzten Update von ism7mqtt und HA läuft das System wieder. Die Verbindung zur Heizung besteht und sendet in MQTT regelmäßig Nachrichten. Diese Nachrichten werden von HA aber nicht mehr in ein Gerät bzw. Entitäten umgewandelt. Sie gehen somit ins leere. 
Ich hatte vermutet die Geräte bzw. Entitäten sind durch das aktive Löschen damals noch irgendwo im System hinterlegt und werden daher nicht neu erstellt. Nach etwas Suche hab ich die passenden Geräte in ../ha-config/.storage in den Daten "core.device.registry" und "core.entity.registry" unter "gelöschte Geräte / Entitäten" gefunden und dort händisch entfernt. Leider hat das auch kein Ergebnis gebracht und HA hat die Geräte nicht erstellt. 

Welche Möglichkeiten gibt es in HA die Geräte noch erstellen/anzeigen zu lassen? 

Installation mit Docker. 

Version | core-2024.9.3
Installationstyp | Home Assistant Container
Entwicklung | false
Supervisor | false
Docker | true
Benutzer | root
Virtuelle Umgebung | false
Python-Version | 3.12.4
Betriebssystemfamilie | Linux
Betriebssystem-Version | 5.4.0-193-generic
CPU-Architektur | x86_64
Zeitzone | Europe/Berlin
Konfigurationsverzeichnis | /config

MQTT Brocker Mosquitto

Bsp. für MQTT Nachrichten die im HA ankommen: 

![image](https://github.com/user-attachments/assets/df5b7658-920e-45bb-911d-c782a1c3bba9)

**Comment by alexkno79** [comment]
Hast du im docker die Environment variable ISM7_HOMEASSISTANT_ID gesetzt, so dass die discover mqtt Nachrichten erzeugt und versandt werden?

**Comment by Sallion00** [comment]
@alexkno79 Vielen Dank für den Tipp. Hat Funktioniert!
