### ISSUE TITLE
Mit v.0.0.17 bekomme ich nicht mehr einzelne Datenpunkte

### ISSUE THREAD

**Issue by Bongo2** [zivillian/ism7mqtt#133]
Eigentlich wollte ich bei diesen Issue nachfragen, weil das Problem immer noch besteht:
https://github.com/zivillian/ism7mqtt/issues/107#issue-2263808497

Habe aber dann gesehen, dass meine Version v0.0.15 veraltet ist und mit der neuesten Version v.0.0.17 versuchen ob mein ursprüngliches Problem vielleicht dadurch gelöst ist.

Ich nutze iobroker mit einem MQTT Server Adapter um die von ism7mqtt gesendete Daten weiterzuverarbeiten.

Aber mit v.0.0.17 (auch bei v.0.0.16) bekomme ich nicht mehr einzelne Datenpunkte, sondern die Daten in einem, ich denke, Json-Format.
Ich habe mal bei den unterschiedlichen Versionen das Debug eingeschaltet und das Log angehängt.

[_ism7mqtt_logs v0.0.15.txt](https://github.com/user-attachments/files/17259583/_ism7mqtt_logs.v0.0.15.txt)
[_ism7mqtt_logs v0.0.16.txt](https://github.com/user-attachments/files/17259587/_ism7mqtt_logs.v0.0.16.txt)
[_ism7mqtt_logs v0.0.17.txt](https://github.com/user-attachments/files/17259590/_ism7mqtt_logs.v0.0.17.txt)

Bei v.0.0.17 habe ich das dazugehörige ism7config laufen lassen.

Wie bekomme ich bei der neuen Version das ursprüngliche Format wieder?

**Comment by zivillian** [comment]
Das liegt an der Änderung, das eine leere HomeAssistantId seit Version v0.0.16 ignoriert wird. Mit dem Parameter `-s` oder der Umgebungsvariable `ISM7_SEPARATE` kannst das Json deaktivieren. Alternativ kannst du auch eine Homeassistant Id setzen.

**Comment by Bongo2** [comment]
Wunderbar. Funktioniert!

Jetzt muss ich noch sehen ob sich das auf mein ursprüngliches Problem positiv auswirkt:
https://github.com/zivillian/ism7mqtt/issues/107#issue-2263808497
