### ISSUE TITLE
kWh readings sometimes off by one after restart 

### ISSUE THREAD

**Issue by binarybucks** [zivillian/ism7mqtt#134]
Hi, 

I'm using ism7mqtt together with Home Assistant in order to track my heatpumps energy consumption over time (among other things). I do have several utility meters defined in Home Assistant that track the delta of e.g the heatpumps yearly energy consumption over time to deduce daily, weekly, monthly, month-before consumption.

I noticed that every few weeks this breaks as there's suddenly a huge delta on some of the values, breaking all kinds of statistics.   

To hunt this down I wrote a simple python script that logs the raw value emitted by ism7mqttm computes a delta from the last received value and notifies me if something seems odd. I have not yet been able to reproduce the issue but caught it several times after restarting ism7mqtt.  

Example: Erzeugte_Waermemenge_aktuelles_Jahr is 6942 at 09:05. Ism7mqtt restarted but reports a lower value of 6941 at 09:07. This causes all utility meters to detect a rollover and the new yearly sum is double the original value. Shortly after, a value of 6942 is received again. 

```
Oct 05 09:05:27 xe python3[2242866]: <<<< Wolf/172.23.13.15/CHA_0x8/Erzeugte_Waermemenge_aktuelles_Jahr: 6942
Oct 05 09:05:27 xe python3[2242866]: >>>> wolf_heatgen_kwh_total.json {'last': 6942.0, 'sum': 12194.0, 'tst': 1728111927.680251}


Oct 05 09:07:41 xe python3[2242866]: <<<< Wolf/172.23.13.15/CHA_0x8/Erzeugte_Waermemenge_aktuelles_Jahr: 6941
Oct 05 09:07:41 xe python3[2242866]:  meter rollover detected
Oct 05 09:07:41 xe python3[2242866]: >>>> wolf_heatgen_kwh_total.json {'last': 6941.0, 'sum': 19136.0, 'tst': 1728112061.177507}

Oct 05 09:15:35 xe python3[2242866]: <<<< Wolf/172.23.13.15/CHA_0x8/Erzeugte_Waermemenge_aktuelles_Jahr: 6942
Oct 05 09:15:35 xe python3[2242866]: >>>> wolf_heatgen_kwh_total.json {'last': 6942.0, 'sum': 19137.0, 'tst': 1728112535.625657}
```

Hence my question, is ism7mqtt doing any computation on these values such that there is an edge case as 6941.9 gets rounded to the next full integer in some cases so the value might jump up or down or are we out of luck and the Wolf firmware is just lazy and reporting broken values now and then?

**Comment by zivillian** [comment]
> is ism7mqtt doing any computation on these values

yes - it's converting them to uint32. The code can be found [here](https://github.com/zivillian/ism7mqtt/blob/29f9e43de8ef65711cad0c2a32905730e4cbf991/src/ism7mqtt/ISM7/Xml/NumericConverter32Template.cs)

> such that there is an edge case 

No - it just takes the four bytes received from the ISM and puts them in the correct order.

You can also enable the debug log in ism7mqtt to see the raw xml received and the value sent via MQTT. The relevant telegram numbers are 10891 and 10892, so you should see something like this:

```
<irs se="A;400" ba="0x8" in="10892" dl="0x0" dh="0x0" st="OK"/>
<irs se="A;401" ba="0x8" in="10891" dl="0x1E" dh="0x1B" st="OK"/>
...
publishing mqtt with topic 'Wolf/172.23.13.15/CHA_0x8/Erzeugte_Waermemenge_aktuelles_Jahr' '6942'
```

**Comment by zivillian** [comment]
I've seen that there should also be "Erzeugte Wärmemenge Vortag". Maybe this is more stable and you can use this.

**Comment by binarybucks** [comment]
Hi, 

thank you. Some counters seem indeed more stable than others, I will try to experiment a bit with them or write a wrapper that catches weird values. 

Thank you for your time.
