### ISSUE TITLE
ism7parameter.exe fails

### ISSUE THREAD

**Issue by omo2002** [zivillian/ism7mqtt#21]
Hi
first of all thank you for this application. But I have an issue generating the parameter.json, when starting the program ism7parameter.exe. I run windows 10 64bit.

Unbehandelte Ausnahme: System.Data.SqlServerCe.SqlCeException: Unable to load the native components of SQL Server Compact corresponding to the ADO.NET provider of version 8876. Install the correct version of SQL Server Compact. Refer to KB article 974247 for more details.
   bei System.Data.SqlServerCe.NativeMethods.LoadNativeBinaries()
   bei System.Data.SqlServerCe.SqlCeConnection..ctor()
   bei System.Data.SqlServerCe.SqlCeConnection..ctor(String connectionString)
   bei ism7parameter.Program.<Main>d__0.MoveNext() in C:\Users\xxx\source\repos\ism7mqtt\src\ism7parameter\Program.cs:Zeile 60.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei ism7parameter.Program.<Main>(String[] args)

I have already installed the SSCERuntime-DEU in the 64bit version. How can I move on ?

**Comment by omo2002** [comment]
Solved it by myself: I had to copy all the files from C:\Users\xxx\AppData\Roaming\Wolf GmbH\Smartset\amd64 to the ism7parameter dir containing the executable file.

**Comment by IgitBuh** [comment]
Thank you for posting your solution! I had the same issue and that solved it.

Shouldn't this step be included in the official instructions?
Maybe those who have "SQL Server Compact" installed on their system don't need to copy those files, but that would be a minority in my opinion.
