### ISSUE TITLE
ism7mqtt for i686 Ubuntu 18.4

### ISSUE THREAD

**Issue by alaska3586** [zivillian/ism7mqtt#28]
My configuration: WOLF system with ISM7 module. The system was cyclicly monitored from a raspberry pi version4 (see closed issue "ism7mqtt on raspberry pi ?" from March 2022) Unfortunately, the raspi broke, and I had to move to another machine using Ubuntu 18.4 . Hardware architecture is i686. Is there an ism7mqtt version running on i686 - in the download section, I was unable to identify other than linux-x64 which cannot be executed on i686.  

Thanks in advance!

**Comment by zivillian** [comment]
sadly the dotnet runtime does not work on x86 (yet) dotnet/runtime#7335
