### ISSUE TITLE
Documentation change

### ISSUE THREAD

**Issue by letsid** [zivillian/ism7mqtt#44]
Hi,
Maybe I just did not find the instruction but I think it should be added , that the ism7parameter archive should be extracted to the install dir of Wolf smartset

%USERPROFILE%\AppData\Roaming\Wolf GmbH\Smartset

br,
letsid

**Comment by zivillian** [comment]
The directory shouldn't matter, since `ism7parameter` automatically tries to read the database from the smartset directory.
