### ISSUE TITLE
Help with writing Times

### ISSUE THREAD

**Issue by alexkno79** [zivillian/ism7mqtt#48]
Hi,

thanks for this great project! i run it on a raspi and successfully receive all data I need.
but I am struggling with writing values which contain times.

e.g when I want to publish a time:

Wolf/192.168.178.64/BM-2_0x35/Uhrzeit_Ende/33006 10:00:00

notthing happens. The same when publishing 

Wolf/192.168.178.64/BM-2_0x35/Uhrzeit_Ende/33006 "10:00:00"

On the other hand I can successfully write values which are numbers. Eg. the following works:

Wolf/192.168.178.64/BM-2_0x35/Urlaubsmodus/value 1

or 

Wolf/192.168.178.64/WWSystem_BM-2_0x35/Warmwassersolltemperatur_eingestellt/35009 50

Can you guide me how for date and time values the message payload needs to look like?

Thanks

**Comment by zivillian** [comment]
[It's not yet implemented](https://github.com/zivillian/ism7mqtt/blob/0ad2d15663f63b05aa9b589e992906a42f513810/src/ism7mqtt/ISM7/Xml/BM2TimeConverterTemplate.cs#L30), because it wasn't a use case until today.

Shouldn't be a big deal - I can add this if needed, but I would be interested in your use case. Can you explain, what you want to achieve?

**Comment by alexkno79** [comment]
Thanks for fast Feedback

Well,  what I try to do is, under certain circumstances to switch off / on my heating based on current weather to prevent the heating from switching on/off all the time (takten).

I currently do this using the smartset API.
 E.g it's sunny. Then I want to put the heating for 1,2 or 4 hours to holiday mode. If indeed I need some more heat on a given day as it is rainy I activate party mode for one or two hours. This way I don't need to trigger auto mode back on or off after the given time as the wolf is doing it autonomously.

**Comment by zivillian** [comment]
Do you prefer a way of setting the date and time?

**Comment by alexkno79** [comment]
Well, for me easiest ist German Notation. Same way as in smartset API:

Ie.
time: HH:mm
Date: DD.mm.yyyy

Below a working JSON to smartset:

{"WriteParameterValues":[{"ValueId":33000800000,"Value":"13:56","ParameterName":"Uhrzeit Start"},{"ValueId":33000900000,"Value":"20.02.2023","ParameterName":"Datum Start"},{"ValueId":33000600000,"Value":"17:56","ParameterName":"Uhrzeit Ende"},{"ValueId":33000700000,"Value":"20.02.2023","ParameterName":"Datum Ende"}],"SystemId":23259,"GatewayId":13902,"BundleId":3600

**Comment by zivillian** [comment]
`13:56` should work

**Comment by alexkno79** [comment]
I tried but no success:

mosquitto_pub -h 127.0.0.1 -t Wolf/192.168.178.64/BM-2_0x35/set/Uhrzeit_Ende/33006 -m "22:02"

But time is not sent back as changed

**Comment by alexkno79** [comment]
error for topic 'Wolf/192.168.178.64/BM-2_0x35' with payload '"22:03"'
CTID '33006' is not yet implemented

**Comment by zivillian** [comment]
Oh, to be clear: I meant `13:56` should work with [the binaries](https://github.com/zivillian/ism7mqtt/actions/runs/4226395367#artifacts) from #49. Your error message looks like your'e still using the binaries from master.

**Comment by alexkno79** [comment]
Year, you were clear, but I was copying the new version but starting the old one ;)
Now running #49 and works perfect!!!!

Thanks, you made my day!

**Comment by alexkno79** [comment]
Hi,

thanks again! Would it be possible as well top implement the date part? 

I e when I try to set date end for Partymode / holiday mode I still receive not supported:

error for topic 'Wolf/192.168.178.64/BM-2_0x35' with payload '21.02.2023'
CTID '33001' is not yet implemented

This would apply to 33001,33007,33009,33003

**Comment by zivillian** [comment]
Can you try [the binaries](https://github.com/zivillian/ism7mqtt/actions/runs/4235866958#artifacts) from https://github.com/zivillian/ism7mqtt/pull/50 and verify that the correct date is set?

**Comment by alexkno79** [comment]
I tried with 33001 and succeeded! Great work! Many thanks!
