### ISSUE TITLE
Download of the Smartset for Windows fails after 6%

### ISSUE THREAD

**Issue by mr-gosh** [zivillian/ism7mqtt#52]
Not your fault - but the download of the Wolf Smartset App fails after 6%

```
22335                           6%[+++                                              ]   3,07M  --.-KB/s    in 0s      

2023-03-10 10:11:42 (0,00 B/s) - Verbindung bei Byte 3214610 geschlossen. Erneuter Versuch.

--2023-03-10 10:11:52--  (Versuch:20)  https://www.wolf.eu/download-asset/22335
Verbindungsaufbau zu www.wolf.eu (www.wolf.eu)|20.103.128.66|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 206 Partial Content
Länge: 46780232 (45M), 43565622 (42M) sind noch übrig [application/x-dosexec]
Wird in ‘22335’ gespeichert.
```

Can't we use the Data out of the SmartSet App on Android - or is the parameters file not generated there?

**Comment by zivillian** [comment]
I've already implemented a new version based on the android app & data. Can you test the binaries from https://github.com/zivillian/ism7mqtt/issues/43#issuecomment-1457083674?

**Comment by jatty** [comment]
If the German website isn't available, here's an alternative download at Wolf Austria with an older Windows version: https://www.wolf-heiztechnik.at/download/?file=5505.exe
