### ISSUE TITLE
Issue with sending set

### ISSUE THREAD

**Issue by copystring** [zivillian/ism7mqtt#53]
Hi,
it's been a while since I looked into this project :) Some things have changed, so I loaded the latest update.

I have a problem with sending data. For example, `Wolf/192.168.1.211/BM_0x35/set/Betriebsart` with payload of 2, 4 or 5 or any other number.
In the log, this shows up:
```
received mqtt with topic 'Wolf/192.168.1.211/BM_0x35/set/Betriebsart' '5'
nothing to send for topic 'Wolf/192.168.1.211/BM_0x35' with payload '5'
```
and `Wolf/192.168.1.211/BM_0x35/Betriebsart/value` is not set to whatever I tried to set it to. I can confirm it did not work via the smart set website.

However, setting `Wolf/192.168.1.211/BM_0x35/set` with payload
```
{
  "Betriebsart":5
}
```
does work perfectly fine. See this log:
```
received mqtt with topic 'Wolf/192.168.1.211/BM_0x35/set' '{
  "Betriebsart":4
}'
> <?xml version="1.0" encoding="utf-16"?><tbreq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" bn="7" gw="1" ae="true" ty="write"><iwr se="" ba="0x30" in="274" dl="0x04" dh="0x00" /></tbreq>
< <?xml version="1.0" encoding="utf-8"?><tbres bn="7" gw="" st="OK" ts="2023-03-13T22:47:36" emsg=""><iac se="0" ba="0x30" in="274" dl="0x4" dh="0x0" st="OK"/></tbres>
publishing mqtt with topic 'Wolf/192.168.1.211/BM_0x35/Betriebsart/value' '4'
publishing mqtt with topic 'Wolf/192.168.1.211/BM_0x35/Betriebsart/text' 'Absenkbetrieb'
```

In my use case, `Wolf/192.168.1.211/BM_0x35/set/Betriebsart` would be a lot easier to use. Can you fix this?

ism7mqtt is run like this: `/usr/bin/ism7mqtt -s -m=192.168.1.242 -i=192.168.1.211 -p=6969696-t=/root/ism7mqtt-linux-x64/parameter.json --separate`

Thank you. Happy to hear back from you.

**Comment by copystring** [comment]
Ah. Has this changed recently?

**Comment by zivillian** [comment]
This was changed for the HA integration. Your screenshot is for json payload - if you scroll down a little, there is an example for single values:

![grafik](https://user-images.githubusercontent.com/6039253/224985205-3f121cd2-6bc2-4458-a2ff-8881e8bf83a0.png)

**Comment by copystring** [comment]
Alright. Thank you. I will try this out later. Closing this assuming this works 👍

**Comment by copystring** [comment]
OK. I tried this just now. Would this be correct? `Wolf/192.168.1.211/BM_0x35/set/Betriebsart/value` with for example payload 4

**Comment by zivillian** [comment]
Yes, this should work.
