### ISSUE TITLE
Error message ism7mqtt

### ISSUE THREAD

**Issue by nekton2** [zivillian/ism7mqtt#56]
Hello,

ism7mqtt reports shortly after start:

`Received empty xml of type 'TgrBundleResp' - skipping dispatch (raw '000000000005')`

At the same time, the MQTT Explorer software, which I currently use for test purposes, is missing devices from the eBus. Is there a connection?

Greetings, nekton2

**Comment by zivillian** [comment]
To be honest, I can't follow your description. How is MQTT Explorer connected to the eBus? What do you mean by "missing devices"?

This warning is logged, when an empty message is received from the ISM. I don't know why and how this happens - as far as I can tell by having reversed the protocol it doesn't make any sense, but maybe it just was to difficult to filter those messages on the ISM or it really is some kind of error.

I'm sorry, but I don't think I can help any further, so I'm going to close this issue. Feel free to reopen if there is something else.
