### ISSUE TITLE
How to correctly setup in Home Assistant?

### ISSUE THREAD

**Issue by airman84** [zivillian/ism7mqtt#64]
Hello,

it would be nice, if anyone could help me setting up ism7mqtt for Home Assistant. I am having a Wolf Link Pro device.
I installed the integration, as well the mosquitto mqtt broker. I created a seperate mqtt user and added the credentials in the mosquitto configuration, but still I receive no new entities from Wolf.

Would please anyone have an idea what could be the problem?
Attached the logs and the ism7-parameters-Wolf.json

[ism7-parameters-Wolf.txt](https://github.com/zivillian/ism7mqtt/files/12122976/ism7-parameters-Wolf.txt)
[logs.txt](https://github.com/zivillian/ism7mqtt/files/12122965/logs.txt)

Thanks for your help
Oliver

**Comment by zivillian** [comment]
I'm sadly busy for the next few days, but I'll take look into this as soon I'm back.

**Comment by airman84** [comment]
Thanks for your replies!
Yes, I have as well configured the MQTT integration,

**Comment by zivillian** [comment]
There is an invalid device in your parameter.json. Can you remove the device with read address `0x15` and try again?

```json
{
  "ReadBusAddress": "0x15",
  "DeviceTemplateId": 0,
  "Parameter": []
}
```

**Comment by airman84** [comment]
Many thanks for your reply, seems that did the trick, really great! I am receiving now 110 entities via MQTT! 😄 
One last question please: On my BM I have the option to trigger "1x Warmwasser", but it's missing in the entitites. Is this already supported or needs configuration?

**Comment by zivillian** [comment]
Can you check if the Smartset App has this option? I don't see `1x Warmwasser` in the paramter.json extracted from your setup.

**Comment by airman84** [comment]
No it's not there. So I guess the issue is with Wolf, as they don't provide it?

**Comment by zivillian** [comment]
Sadly yes - you can try to ask Wolf if there is something wrong with your setup, since the BM supports it.
