### ISSUE TITLE
MQTT QOS 

### ISSUE THREAD

**Issue by Eba-M** [zivillian/ism7mqtt#69]
Leider kann ich die eingehenden Nachrichten, in meinem Programm nicht empfangen, da vom Publisher der QOS auf 0 gesetzt ist. Damit nützt mir die ganze Sessionverwaltung von meinem MQTT Broker nichts. Ich schaue ca. 1x in der Minute nach, ob eine Nachricht vorliegt, ist das nicht der Fall, beende ich die Abfrage. Zwischenzeitlich eingegangene Nachrichten werden nicht weitergeleitet und sind somit für mich verloren.
Also bitte QOS auf 1 oder 2 setzten oder beim Aufruf vom ism7mqtt als parameter übernehmen (z.B. -p 1)

**Comment by Eba-M** [comment]
queue_qos0_messages [ true | false ]

Diesen Parameter kann man am Broker setzen, damit werden auch eingehende QOS 0 in die messages queue eingereiht.

**Comment by zivillian** [comment]
Ich habe einen Parameter hinzugefügt mit dem der QoS konfiguriert werden kann. Kannst du einmal die Binaries aus dem [qos branch](https://github.com/zivillian/ism7mqtt/actions/runs/6486799586?pr=71#artifacts) testen und prüfen ob es damit funktioniert?
