### ISSUE TITLE
missing feature: mqtt authentication

### ISSUE THREAD

**Issue by maximilianriess** [zivillian/ism7mqtt#7]
Hi,

thanks for the great job on this tool!
It would be great if the mqtt-connection could be parameterized with username and password.
:)

have a nice day!
Maximilian

**Comment by zivillian** [comment]
Hi Maximilian,

this should be fixed in the latest [build](https://github.com/zivillian/ism7mqtt/actions/runs/857935107#artifacts), but I'm not able to test this. I've added two additional parameter - `mqttuser` and `mqttpass`. Can you test and report, if this works?

**Comment by maximilianriess** [comment]
Hi!

i've successfully verified it on a Debian Buster System against a mosquitto mqtt running on a Raspbian with authentication enabled. It works fine!  🥇 

Thanks and kind regards, 
Maximilian
