### ISSUE TITLE
Parameters for mixed heating circuits missing?

### ISSUE THREAD

**Issue by click3dm** [zivillian/ism7mqtt#72]
I have a Wolf CBG-20 with one direct heating circuit (Direkter Heizkreis) and two mixed valve heating circuits (Mischermodul 1 and 2).
I can control via Smartset App for each of these 3 heating circuits e.g. the program (Automatic, Standby, ...). 
However via ism7mqtt, there is only the parameter for the direct heating circuit available:
DHK_BM-2_0x35_Programmwahl_340029_value
DHK_BM-2_0x35_Programmwahl_340032
(why are there two?)

For the mixed circuits (MM_0x51 and MM_0x52), there are several values available in ism7mqtt, but no "Programmwahl" or similar?
Why that? How can you control the program state of the several circuits?

(Similar also for the parameter DHK_BM-2_0x35_Sollwertkorrektur_340026; DHK_BM-2_0x35_Sollwertkorrektur_340031 - not available for MM_0x51 and MM_0x52)

**Comment by zivillian** [comment]
Can you show a screenshot of the controls in the app and also post your parameters.json?

**Comment by click3dm** [comment]
[parameter.json](https://github.com/zivillian/ism7mqtt/files/12908871/parameter.json)
![2023-10-15_09h13_01](https://github.com/zivillian/ism7mqtt/assets/147931074/77a4518f-a704-40a8-a4eb-bfefbf916003)

I hope the attached screenshots works for you.

**Comment by zivillian** [comment]
That helped - I was able to reproduce the issue. The missing properties are part of two additional _virtual_ devices, which are not part of the initial system config response. I've changed the startup to just use all devices from the parameter.json instead of requesting the devices.

Can you try the [binaries from the PR](https://github.com/zivillian/ism7mqtt/actions/runs/6524213139/?pr=73#artifacts)? You must also create a new parameter.json, otherwise you will get errors when writing due to an incorrect bus address.

**Comment by click3dm** [comment]
Thanks a lot, it looks already better, but not 100% perfect.

I now get a lot of values for MK_BM-2_0x85. That looks quite good already.
However, there are only a few values for MK_BM-2_0x86 (Raumtemperatur_360124, Tagtemperatur_360086, Tagtemperatur_360093, Tagtemperatur_360110).

Moreover, my MQTT Filelog shows at one timestamp
MK_BM-2_0x85_Heizkreis_Benamung: MM 1
A little later it shows
MK_BM-2_0x85_Heizkreis_Benamung: MM2

So it seems to me somehow, they get mixed up, right?

Updated parameter.json:
[parameter.json](https://github.com/zivillian/ism7mqtt/files/12910299/parameter.json)

**Comment by zivillian** [comment]
Thanks for the feedback - this sounds really strange. Can you create and upload a debug log  with the two properties `Benamung: MM 1` and `Benamung: MM2` (just run ism7mqtt with the additional parameter `-d` and remove your password before uploading).

**Comment by zivillian** [comment]
After looking at the code, I think I've found the bug - currently there is only a single instance for each ConverterTemplate and ParameterDescriptor. Since you have two identical devices with the same parameters, the instances are reused and thus the values are always reported at the first instance.

**Comment by zivillian** [comment]
I've pushed an update which clones the ConverterTemplates - the [new binaries](https://github.com/zivillian/ism7mqtt/actions/runs/6526953422?pr=73#artifacts) should be available in a few minutes. Please let me know if this now reports the values for each MK.

**Comment by click3dm** [comment]
Thanks a lot!
Funnily I do not get any MQTT communication anymore:

`> <?xml version="1.0" encoding="utf-16"?><direct-logon-request xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><password>XY</password></direct-logon-request>
< <?xml version="1.0" encoding="utf-8"?><direct-logon-response state="ok" sid="1"><installationname>WolfLink</installationname><serialnumber>XY</serialnumber><date-time>2023-10-16T08:49:18</date-time><ism-softwareversion>300.10.1.300.300.1</ism-softwareversion><ism-hardwareversion>3.0</ism-hardwareversion><type>WOLFLink</type><wlan-connected>true</wlan-connected></direct-logon-response>
> <?xml version="1.0" encoding="utf-16"?><tbreq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" bn="1" gw="1" ae="false" ty="pull"><ird in="0" se="" ba="0x00" /><ird in="0" se="" ba="0x00" /><ird in="0" se="" ba="0x00" /><ird in="0" se="" ba="0x00" /></tbreq>
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument )
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 , Func`2 )
   at ism7mqtt.ISM7.Xml.MultiTelegramConverterTemplateBase.get_InfoReads() in /home/runner/work/ism7mqtt/ism7mqtt/src/ism7mqtt/ISM7/Xml/MultiTelegramConverterTemplateBase.cs:line 14
   at ism7mqtt.Ism7Config.RunningParameter.get_InfoReads() in /home/runner/work/ism7mqtt/ism7mqtt/src/ism7mqtt/ISM7/Ism7Config.cs:line 332
   at ism7mqtt.Ism7Config.RunningDevice.<>c.<get_InfoReads>b__18_0(RunningParameter x) in /home/runner/work/ism7mqtt/ism7mqtt/src/ism7mqtt/ISM7/Ism7Config.cs:line 205
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 , IEnumerable`1 )
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at ism7mqtt.Ism7Client.LoadInitialValuesAsync(CancellationToken cancellationToken)
   at ism7mqtt.ResponseDispatcher.DispatchAsync(IResponse response, CancellationToken cancellationToken) in /home/runner/work/ism7mqtt/ism7mqtt/src/ism7mqtt/ISM7/ResponseDispatcher.cs:line 32
   at ism7mqtt.Ism7Client.ReadPipeAsync(PipeReader source, CancellationToken cancellationToken) in /home/runner/work/ism7mqtt/ism7mqtt/src/ism7mqtt/ISM7/Ism7Client.cs:line 212
`

current parameter.json:
[parameter.json](https://github.com/zivillian/ism7mqtt/files/12913039/parameter.json)

**Comment by zivillian** [comment]
Sorry, it was late and I've missed some classes for the `Clone` implementation. I've pushed a fix (which hopefully is complete this time).

Can you try [the new binaries](https://github.com/zivillian/ism7mqtt/actions/runs/6553016590?pr=73#artifacts) again?

**Comment by click3dm** [comment]
Perfect, this looks very well at a first glance.

Thank you so much!
