### ISSUE TITLE
Partymodus und Urlaubsmodus

### ISSUE THREAD

**Issue by jatty** [zivillian/ism7mqtt#74]
Diverse Textfelder werden von der Heizung per ism7mqtt übertragen:

Partymodus:
text.wolf_bm2_0x30_330000_uhrzeit_ende "19:49:00"
text.wolf_bm2_0x30_330001_datum_ende "10/15/2023 00:00:00"
text.wolf_bm2_0x30_330002_uhrzeit_start "16:49:00"
text.wolf_bm2_0x30_330003_datum_start "10/15/2023 00:00:00"

Urlaubsmodus:
text.wolf_bm2_0x30_330008_uhrzeit_start "19:49:00"
text.wolf_bm2_0x30_330007_datum_ende "10/15/2023 00:00:00"
text.wolf_bm2_0x30_330008_uhrzeit_start "16:49:00"
text.wolf_bm2_0x30_330009_datum_start "10/15/2023 00:00:00"

Diese scheinen aber nur in diese eine Richtung zu funktionieren.

Ein Schreibversuch des Textfeldes in die Gegenrichtung zur Heizung hin scheitert.
Auf dem MQTT-Bus werden sie erfolgreich übertragen:

Wolf/BM-2_0x35/set/Uhrzeit_Start/330002 "12:45:56"
Wolf/BM-2_0x35/set/Uhrzeit_Ende/330000 "22:22:22"

... jedoch verbleiben im BM-2-System weiterhin die alten Werte.

Dazu kommt, dass die Datums-Werte auch die Uhrzeit mitführen. Ich weiß nicht, ob das ein Bug oder Feature (1:1 von ISM7?) ist.

**Comment by zivillian** [comment]
Das Problem ist, dass ich nicht weiß, wie genau die Daten gesendet werden müssen. Hast du Zeit und Lust mit dem ism7proxy und der Wolf App ein Logfile zu erstellen, in dem man sieht, was gesendet werden muss wenn Datum und Uhrzeit geschrieben werden?

**Comment by jatty** [comment]
Ja klar, gerne. Wie kann ich mich da am besten vorantasten?

**Comment by zivillian** [comment]
Ich hab das in der github action ergänzt - du kannst einfach [die Binaries aus dem letzten Build](https://github.com/zivillian/ism7mqtt/actions/runs/6600166088#artifacts) nehmen. In Zukunft sind die auch in der Releases dabei.

**Comment by alexkno79** [comment]
klappt bei mir reibungslos:

Beispiel von eben grade bei mir für Urlaubsmodus (hier per mosquitto client an MQTT broker bei mir der .63 an die Wolf (hier die .64):
mosquitto_pub -h 192.168.178.63 -t Wolf/192.168.178.64/BM-2_0x35/set/Datum_Ende/330007 -m 11/14/2023
mosquitto_pub -h 192.168.178.63 -t Wolf/192.168.178.64/BM-2_0x35/set/Uhrzeit_Ende/330006 -m 23:26
mosquitto_pub -h 192.168.178.63 -t Wolf/192.168.178.64/BM-2_0x35/set/Urlaubsmodus/value -m 1

Party funktioniert genauso.

**Comment by zivillian** [comment]
@alexkno79 danke für's testen!

@jatty kannst du das nochmal bei dir prüfen?
