### ISSUE TITLE
Fehlende Entitäten Wolf MM

### ISSUE THREAD

**Issue by Reudo** [zivillian/ism7mqtt#75]
Hi,
ich hatte vor einigen Monaten schon mal einen Post wegen fehlender Entitäten bei meiner Wolf Anlage.
Dadurch, dass diese parameter Datei nicht mehr benötigt wird (?) ,dachte ich es wären jetzt alle da.

Die Werte sind hier zu finden:
/ Fachmann / Mischermodul MM1

![Screenshot 2023-10-21 145118](https://github.com/zivillian/ism7mqtt/assets/48895679/2fdb3219-45c0-488a-a562-1def477e8b6e)

Und hier noch die Dinger in einem anderen Menü:
/ Fachmann / Bedienmodul BM-2 0

![Screenshot 2023-10-21 145621](https://github.com/zivillian/ism7mqtt/assets/48895679/7dd85c9e-1ed7-4402-bb02-9f62517be842)

![image](https://github.com/zivillian/ism7mqtt/assets/48895679/9beb64a6-ad59-4f85-9e62-5d969a618722)

Wenn ich irgendwie bei der Fehlersuche helfen kann, sag bescheid. 

Edit: Achso als kleine Info noch: Ich benutze das https://github.com/b3nn0/hassio-addon-ism7mqtt 
Sollte aber vermutlich keinen Unterschied machen?

**Comment by zivillian** [comment]
Das hatten wir gerade erst in #72. Kannst du einmal testen, ob [die Binaries ](https://github.com/zivillian/ism7mqtt/issues/72#issuecomment-1767220786)das Problem auch bei dir lösen? Ich habe den Code zwar schon im master, aber es gibt noch kein neues Release - das wollte ich die Tage mal fertig machen

**Comment by Reudo** [comment]
Sieht gut aus. Hab eben nochmal die parameter Datei generiert und das ism7mqtt gestartet. Hab zwei neue Geräte dazu bekommen. 

Allerdings habe ich jetzt gerade wieder massenhaft doppelte Entitäten.

![image](https://github.com/zivillian/ism7mqtt/assets/48895679/b3bb2ae5-56ea-481e-913d-c8cdd558aa5a)

Offenbar hat sich da wieder etwas in den Bezeichnungen geändert.

Hier mal ein Beispiel:
sensor.wolf_cgb2_0x3_180141_typ
sensor.wolf_cgb2_0x03_180141_typ

**Comment by zivillian** [comment]
Die Änderungen sind jetzt auch im aktuellen Release enthalten - daher würde das schließen.

Ich versuche die Namen stabil zu halten, aber durch die Umstellung von der Smartset Applikation auf die Mobile App hat sich sich auch bei Wolf einiges verändert.

Sollte noch was fehlen, oder auffallen, einfach ein neues Issue aufmachen.

**Comment by Reudo** [comment]
Danke. Wie war das nochmal mit dem Ism7MQTT HA Addon? Muss ich da eine neue parameter Datei generieren oder so?

**Comment by zivillian** [comment]
Um sicher zu gehen, ja. Es gibt in der parameter.json einen neuen Parameter `WriteBusAddress` - ich habe zwar einen Fallback eingebaut, so dass es auch geht, wenn der nicht vorhanden ist, aber das könnte in deinem Fall zu Problemen führen.

**Comment by Reudo** [comment]
Hat soweit geklappt 👍

Das hier ist immer noch alles Unknown aber brauche ich auch absolut nicht.
Sind nur Parameter vom ISM selbst.
![image](https://github.com/zivillian/ism7mqtt/assets/48895679/e27f782b-0e4c-4798-acec-b94230316f7d)
