### ISSUE TITLE
Can't write values anymore after some time

### ISSUE THREAD

**Issue by airman84** [zivillian/ism7mqtt#77]
Hello,

I am running ism7mqtt on Home Assistant. I frequently run into the issue, that I can't write values anymore after some time. At same time, I still receive status updates of the sensors, so the connection seems to be fine. When checking the ism7mqtt protocol, there is not any trace about my intended value change. When restarting ism7mqtt, everything is back to normal.

Do you have any idea? How and what logs could I provide?

Thank you
Oliver

**Comment by Reudo** [comment]
Are you still using smartset or the wolf app? I've noticed the same but only if I used one of them.

**Comment by airman84** [comment]
No, I am not using any of those anymore

**Comment by zivillian** [comment]
This sounds, like the MQTT connection was lost and either not reconnected, or it didn't subscribe again. Can you check if you can reproduce this by just restarting your mqtt broker?

**Comment by airman84** [comment]
I came over the same issue again and somehow it can solve itself, but it takes some minutes until the set value is then considered. To me it seems there was an error, ism7mqtt crashed and restarted, afterwards the value was taken. But when trying to change now the value again, it's still producing the same exception. 

Restarting the MQTT broker does not solve the problem, same exception is shown in the log, when trying to set the value. Only restart of ism7mqtt helps. Attached is the parameters 

file and the log file, starting with setting the requested value. This happens more or less every day to me.

Set value: 
received mqtt with topic 'Wolf/192.168.2.45/BM_0x35/set/Eingestellte_Warmwassersolltemperatur' '15'

System.ArgumentException: '0xFFFFFFFB' is not a hex value (Parameter 'hex')

After the exception, this is received:
publishing mqtt with topic 'Wolf/192.168.2.45/BWS-1_0x8/T_WWasser_soll' '15'

[log.txt](https://github.com/zivillian/ism7mqtt/files/13257265/log.txt)
[ism7-parameters-Wolf.json](https://github.com/zivillian/ism7mqtt/files/13257266/ism7-parameters-Wolf.json)

**Comment by airman84** [comment]
After deleting the parameters file and the new one has been created, it seems to work now again. Not sure if that will fix also my problem, when writing of values was not possible anymore after some time. If not, I will report again.

Many thanks for your efforts!
