### ISSUE TITLE
Parameter "Port" for an external MQTT server

### ISSUE THREAD

**Issue by BaZQ** [zivillian/ism7mqtt#78]
Hi,

first of all many thanks for your work!
I use the Home Assistant addon from b3nno, to send the data from Home Assistant to an external MQTT server, an additional parameter is needed to set a specific port, this is different from "1883".

Can you please add a parameter for the port when you get a chance?
b3nno has already added parameters for the external IP, user, password in his addon -> https://github.com/b3nn0/hassio-addon-ism7mqtt/issues/34

Greetings

**Comment by zivillian** [comment]
fixed in https://github.com/zivillian/ism7mqtt/commit/9dd969dac3ab82a6814a1291f3b239c5f8fddefd

**Comment by BaZQ** [comment]
That was fast, thanks for the support!!! :)
