### ISSUE TITLE
Duplicated entries

### ISSUE THREAD

**Issue by Morcman** [zivillian/ism7mqtt#86]
Hi there,

after updating to one of the newest releases I get duplicated entries for Wolf_CHA within homeassistant. Ones are starting with the topic Wolf_CHA_0x03_27XXX and the others with the topic Wolf_CHA_0x3_27XXX. Attachted is a screenshot from MQTTExplorer:
![image](https://github.com/zivillian/ism7mqtt/assets/99669483/3e76d826-54c9-4658-a76a-146f09e23be2)

![image](https://github.com/zivillian/ism7mqtt/assets/99669483/6f0155e2-c902-442f-84ca-385d00eae60a)

There are also duplicated entries for the iSM7 but all of those are unknown unfortunatly: 
![image](https://github.com/zivillian/ism7mqtt/assets/99669483/e8f6c192-6f79-417d-96a7-1dcd3e105c4a)

![image](https://github.com/zivillian/ism7mqtt/assets/99669483/57c13985-d29e-4f70-b26a-3de4e91b99c8)

![image](https://github.com/zivillian/ism7mqtt/assets/99669483/30d3e92c-4b69-40f2-ac76-187904f8c7a0)

**Comment by zivillian** [comment]
there was a breaking change, which changed the busaddresses of the devices - you can safely delete the MQTT topics and the old entities in HA.
