### ISSUE TITLE
Punkte machen Probleme im iobroker

### ISSUE THREAD

**Issue by Klaus-Lucas** [zivillian/ism7mqtt#89]
Hallo,

ich nutze iobroker mit einem MQTT Server Adapter um die von ism7mqtt gesendete Daten weiterzuverarbeiten.
Aufgerufen wird es mit dem Parameter --seperate.
Dabei sorgen die Punkte für Verwirrung. Gesendet wird (hier als json zu besseren Darstellung):
```json
},
"Energie VT (el.)": 9,
"Energie VT (th.)": 47,
"Energie VT (TAZ)": 5.2,
"Energie HP (el.)": 1526,
"Energie HP (th.)": 7765,
"Energie HP (JAZ)": 5.1,
"Energie VJ (el.)": 956,
"Energie VJ (th.)": 6548,
"Energie VJ (JAZ)": 6.8,
```
Im iobroker sieht das so aus:
![grafik](https://github.com/zivillian/ism7mqtt/assets/36620907/3f34f977-f772-41c5-b3d1-d560aacc0fda)

![grafik](https://github.com/zivillian/ism7mqtt/assets/36620907/f4cd11de-7f08-46dc-8627-f3c7fbe930ce)

![grafik](https://github.com/zivillian/ism7mqtt/assets/36620907/c3d25778-cbb8-4d77-9e8f-bdc7448687db)

Wäre es möglich, dass die Punkte, wie schon beim Slash, durch Unterstriche zu ersetzen?

**Comment by zivillian** [comment]
wenn ich das richtig sehe ist es nicht die Klammer, sondern der Punkt der Probleme bereitet:
![grafik](https://github.com/zivillian/ism7mqtt/assets/6039253/0d477b18-a00b-40c6-a799-219f7df56957)
zwischen `(th` und `)` kommt eigentlich noch ein Punkt:

```json
"Energie VT (el.)": 9,
"Energie VT (th.)": 47,
"Energie VT (TAZ)": 5.2,
```

Ich möchte die Namen nur sehr ungern ändern, da das bei allen anderen Nutzern zu neuen zusätzlichen Entitäten führt.

Kannst du nochmal prüfen, was genau das Problem ist und ob es noch eine andere Möglichkeit gibt?

**Comment by Klaus-Lucas** [comment]
Da hast du natürlich Recht, dass der Punkt das Problem ist.
Lass es erstmal so wie es ist. Ich frage mal bei den [MQTT Adapter](https://github.com/ioBroker/ioBroker.mqtt) Betreuer nach, wie sie das sehen.

**Comment by zivillian** [comment]
Ich mach das hier erstmal zu - mach das gern wieder auf, wenn es etwas neues gibt. Dann können wir immernoch überlegen ob und wie sich das am besten integrieren lässt.
