### ISSUE TITLE
Device Template not found

### ISSUE THREAD

**Issue by feuse8** [zivillian/ism7mqtt#9]
Hi,

I've been trying to get it work with ism7-e. I tried it on Windows and also on a CentOS VM. I have a Wolf ism7-e, BWM-1 and BWS-1. Sometimes the values are read but most of the times the application is just crasing / finishing after one try. No values are sent to my MQQT Queue / even the topics are not created. Am I missing some important configuration? Pls find attached my Files.

Thanks for your help
[ism7.zip](https://github.com/zivillian/ism7mqtt/files/7964899/ism7.zip)
.

**Comment by zivillian** [comment]
From the debug log it looks like it should be supported. I guess there is an unsupported parameter on one of your devices. Could you try with only a single device (one after the other) until you find the broken device? Please be aware, that the ISM7 might need a few seconds (or one minute), before accepting a new connection after a disconnect.

**Comment by zivillian** [comment]
You can also just try the 0.0.4 release (published just now). This includes debug output for the unsupported `UnicodeTextConverter` which already caused trouble. If you see `UnicodeTextConverter T:<...> H:<...> L:<...>` in the output you are also affected. If H differs from 128 or L differs from 0 I would like to get the log, so I can finally implement this converter.

**Comment by feuse8** [comment]
Hi, I tried to create a minimal Configuration with only 1 Value in the JSON. The Reconnect now seems to work reliably. But a MQTT entry is not created and every time I execute the application, it's always closing after 1 read attempt.
[ism7.zip](https://github.com/zivillian/ism7mqtt/files/7974435/ism7.zip)
.

**Comment by feuse8** [comment]
Ok I started to debug and it seems there is no device template for the following device:
<busDevice ba="0x8" sv="0x80" sr="0x0" cfg="0x405A" did="0x1E"/>

**Comment by zivillian** [comment]
That's interesting. Looks like there is another way to get the parameter for each device. Adding it to the XML file is not the solution - those are the latest config file from the Smartset app.
I'll look into this, but I may take while...

**Comment by zivillian** [comment]
This was easier than expected. Can you test the build from https://github.com/zivillian/ism7mqtt/actions/runs/1785869727? If this works, I will merge the PR.

**Comment by feuse8** [comment]
Cool! Thanks a lot!

Seems to work better except for one situation: the system sends data from ba 0x15 which has no corresponding entry in the parameters.json. This causes the app to crash. I fixed it for me by replacing .first()  with firstOrDefault() in the ISM7Config addDevice and by adding a check if the key exists in GetTelegramIdsForDevice.

**Comment by feuse8** [comment]
Looks like _config.Devices is not contained in the JSON File. I created two Screenshots. Maybe they can help. Otherwise it would be cool if you could tell me how to create the Trace. 

The bus device info is:
`<busDevice ba="0x15" sv="0x2" sr="0x4" cfg="0x0" did="0x18"/></busDevices>`

![AddDevice](https://user-images.githubusercontent.com/20636203/152246299-fab0a834-9dd8-426f-a090-6f0c5a365e6d.PNG)
![OnSystemConfigAsync](https://user-images.githubusercontent.com/20636203/152246303-3fa427e1-0275-4392-974c-72b99264d024.PNG)

**Comment by zivillian** [comment]
By trace I just meant the debug log, but I know what the problem is. You are correct, that invisible devices are not included in the parameter.json, but they also have a DeviceTemplateId `0` which is not included in the `DeviceTemplates.xml`. I'll add a check and update the PR.

**Comment by zivillian** [comment]
Can you test again with https://github.com/zivillian/ism7mqtt/actions/runs/1786535340?

**Comment by feuse8** [comment]
Thanks a lot! Now it works like a charm!

**Comment by zivillian** [comment]
There will soon be a new release, but I'd like to wait for #10 / #12
