### ISSUE TITLE
Parameter file creation seems to have failed. Please report to the ism7mqtt project: 

### ISSUE THREAD

**Issue by lefgrter** [zivillian/ism7mqtt#90]
Hi, I am trying to setup in HA, but after 2 minutes of trying to create the parameters file the log turns like below:

"12/18/2023 22:16:48: Timeout waiting for GW
Parameter file creation seems to have failed. Please report to the ism7mqtt project: https://github.com/zivillian/ism7mqtt/issues/new
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped"

My problem is that also PC app cannot connect  and my mobile app can't connect locally.  My only access to the system is thorough the portal. I have even upgraded the firmware of the ISM to 3.20, but nothing.

After searching a bit I managed to find an older version of the PC app from 2019, this one can allow my PC to connect to the ISM

As I have access to spare parts, I tried to use another ISM7 (Link home) but I have the same problem. I am expecting now to test a pro version (the external one) 

Maybe my system is to complicated? 
I have 2 X BWL-1S heat pumps in Cascade mode with the corresponding Module, 7 X MM Mixing units, a solar system (BM-2 Solar) and a pool heater.

Has any one faced the same problem with me?

I would appreciate any feed back

**Comment by zivillian** [comment]
Sorry to hear that. Since you can't use the official Smartset app (which uses the same logic as the ism7config tool), I'd suggest you contact wolf. I think one of the components on the bus is misbehaving or not responding in time.

**Comment by lefgrter** [comment]
Thank you for your answer. I am preparing an email to the company of course, but I thought that maybe someone else is Experiencing a similar issue. The strange think is that portal and app access from internet works perfectly.
Thanks again
