### ISSUE TITLE
Kesselsolltemperatur nicht auslesbar

### ISSUE THREAD

**Issue by Kalemus** [zivillian/ism7mqtt#96]
(Auch hier an richtiger Stelle nochmal vielen Dank für die tolle Arbeit)

Die KesselSOLLtemperatur wird offenbar nicht korrekt ausgelesen ober übermittelt und steht dauerhaft auf "Unknown". Die KesselISTtemperatur wird problemlos übertragen.

Du wolltest die parameter.json und debug output. Bin jetzt leider noch nicht ganz so fit in dem Zeug, hab dir die ism7-parameter Datei angehängt. Beim Debug hab ich die Debugprotokollierung des Addons laufen lassen, hoffe das war richtig, außerdem noch die Diagnoseinformationen des Addons. Sonst bitte kurz sagen, wo genau ich suchen muss. Sorry für den Aufwand!

Danke :-)

[config_entry-mqtt-d500dedfc1173acdfc238dc16dd4117a (1).json](https://github.com/zivillian/ism7mqtt/files/14424595/config_entry-mqtt-d500dedfc1173acdfc238dc16dd4117a.1.json)
[home-assistant_mqtt_2024-02-27T19-04-36.302Z.log](https://github.com/zivillian/ism7mqtt/files/14424597/home-assistant_mqtt_2024-02-27T19-04-36.302Z.log)

[ism7-parameters-Wolf.json](https://github.com/zivillian/ism7mqtt/files/14424292/ism7-parameters-Wolf.json)

**Comment by zivillian** [comment]
Auf den ersten Blick sieht das alles richtig aus. Kannst du einmal mit MQTT Explorer schauen ob die eine Nachricht auf dem Topic `Wolf/192.168.178.68/CGB-2_0x8/Kesselsolltemperatur` siehst, wenn du das Addon neu startest? Die Solltemperatur ändert sich bei dir wahrscheinlich relativ selten und ism7mqtt sendet nur bei Änderung. Beim Start werden aber alle Werte einmal abgefragt.

Wenn du da nix siehst müssten wir tiefer schauen. Dafür bräuchte ich dann einen [Debug Log](https://github.com/zivillian/ism7mqtt?tab=readme-ov-file#bugs--missing-features). Leider kann ich dir nicht sagen, ob und wie du den mit den HA Addon erstellen kannst. Im schlimmsten Fall müsstest du ism7mqtt einmal außerhalb von HA zum laufen bekommen.

**Comment by Kalemus** [comment]
Sorry für die späte Meldung, war arbeitstechnisch stark eingespannt. Ich hab mal nachgeschaut und die Kesselsolltemperatur ist bereits direkt nach dem Reset auf "Unknown". Die Temperatur ändert sich übrigens im gleichen Maß wie die Außentemperatur, also tatsächlich sehr regelmäßig.
Leider habe ich zu wenig Ahnung, wie ich das ism7mqtt außerhalb von HA zum Laufen bekomme und ich möchte auch ungern deine Lebenszeit damit verschwenden, dass du ständig Dinge nachfragst. Ich habe eine andere Methode gewählt, die vielleicht für andere auch interessant sein könnte, falls der Kesselsollwert dort nicht übertragen wird.

Die Berechnung der Solltemperatur ist nämlich relativ einfach und basiert auf einigen Parametern der Heizkurve. Diese werden einwandfrei über dein Addon übertragen und sind im HA verfügbar. Damit kann man problemlos den Kesselsollwert selbst ausrechnen und dynamisch ändern lassen. Ich hänge das Teil mal hier an. Damit kann ich bei mir die alte Darstellung aus der Wolf-Software nachbilden und Solltemperatur und IST-Temperatur vergleichen. 

Danke dir für deine ganze Mühe!

(In der configuration.yaml)

template:
  - sensor:
    #Berechnete Kesselsolltemperatur
      - name: "Kesselsolltemperatur"
        unique_id: "WolfKesselSollT"
        unit_of_measurement: "°C"
        state_class: "measurement"
        state: >
             {{ (float(states('number.wolf_dhk_bm2_0x30_340015_vorlauftemperatur_heizkurve')) -
             float(states('number.wolf_dhk_bm2_0x30_340012_sockeltemperatur_heizkurve'))) /
             (float(states('number.wolf_dhk_bm2_0x30_340014_normaussentemperatur_heizkurve')) -
              float(states('number.wolf_dhk_bm2_0x30_340013_startpunkt_heizkurve'))) * 
             (float(states('sensor.wolf_dhk_bm2_0x30_340001_gemittelte_aussentemperatur')) -
             float(states('number.wolf_dhk_bm2_0x30_340013_startpunkt_heizkurve'))) +
             float(states('number.wolf_dhk_bm2_0x30_340013_startpunkt_heizkurve')) +
             (float(states('number.wolf_dhk_bm2_0x30_340015_vorlauftemperatur_heizkurve')) -
             float(states('number.wolf_dhk_bm2_0x30_340012_sockeltemperatur_heizkurve'))) / 10 *
             float(states('number.wolf_dhk_bm2_0x30_340028_sollwertkorrektur'))}}
