### ISSUE TITLE
Einige Parameter/Werte werden nicht abgerufen CGB-2-14 (hassio Addon)

### ISSUE THREAD

**Issue by ottelo9** [zivillian/ism7mqtt#98]
Ich verwende das [hassio Addon](https://github.com/b3nn0/hassio-addon-ism7mqtt) um die Daten meiner Gastherme in HA anzuzeigen. Vorher hatte ich dort die Wolf Integration verwendet, das ging ja bis vor kurzem problemlos.

Die Portal Funktion habe ich in ISM7 deaktiviert, damit ism7mqtt funktioniert. Ansonsten kamen nur 1x Daten vereinzelt rein und das wars. ISM7 hat auch paarmal neugestartet, war wohl überfordert. Das ganze betreibe ich über WiFi.

**Nun zum Problem:**
Das Addon legt in HA 5 MQTT Devices an
![image](https://github.com/zivillian/ism7mqtt/assets/33122175/4feca003-a185-4e4e-a595-ec8ad2c71e98)

Unter dem Device _Wolf CGB-2_ sind einige Parameter/Werte _Unknown_ findet er also nicht. Ich habe schon viele deaktiviert, die ich nicht brauche. Auf dem Bild sind aber welche, die ich gerne hätte (z.B. Kesselsolltemperatur).
![image](https://github.com/zivillian/ism7mqtt/assets/33122175/0cc8ba38-bd85-415c-b9b1-88d420a8923d)

Unter dem Device _Wolf ISM_ ist alles komplett unbekannt / nicht gefunden:
![image](https://github.com/zivillian/ism7mqtt/assets/33122175/23a84cfe-0b7e-42a1-bbfe-bb8557cb438e)

Ich habe ISM7 FW2.10 CGB-2-14. Wie Wifi Verbindung zum Modul ist astrein und er zeigt mir auch die Direkte Verbindung an. Hier ist der Debuglog aus dem Hassio Addon. Vielleicht hilft es weiter.

https://pastebin.com/b6pMJrY7

Im [Hassio Addon Repo](https://github.com/b3nn0/hassio-addon-ism7mqtt/issues/44) weiß man leider auch kein Rat.

**Comment by zivillian** [comment]
kannst du noch die `parameter.json` dazu hochladen?

**Comment by ottelo9** [comment]
Wo finde ich diese beim Hassio Addon?

**Comment by zivillian** [comment]
Ich nutze das Addon nicht, daher bin ich überfragt.
@b3nn0 kannst du helfen und sagen, wie man in HA and parameter.json kommt?

**Comment by ottelo9** [comment]
@zivillian 
[ism7-parameters-Wolf.json](https://github.com/zivillian/ism7mqtt/files/14626300/ism7-parameters-Wolf.json)

**Comment by zivillian** [comment]
kannst du einmal testen was passiert, wenn du bei dem CGB-2 Gerät alle Parameter außer der Kesselsolltemperatur entfernst?

```json
...
    {
      "ReadBusAddress": "0x8",
      "WriteBusAddress": "0x3",
      "DeviceTemplateId": 180000,
      "Parameter": [
        180154
      ]
    }
...
```

Aktuell werden bei dem Device über 100 Register abgefragt - ich vermute, dass es einfach zu viele sind.

**Comment by Rezessivo** [comment]
Hallo @zivillian, ich habe ähnliche Probleme wie @ottelo9. Allerdings habe ich einen COB-20 im Einsatz.
mich interessiert eigentlich nur 1 Wert und das ist die aktuelle Warmwassertemperatur...diese ist aber komischerweise gar nicht vorhanden...(wobei fast alles auf "unknown" steht, einzig der Abschnitt mit Solar zeigt alle Werte korrekt an)
sieht man irgendwo, welche Template ID für welches Gerät steht und welche Parameter, welche Ziffernfolge ist???

**Comment by zivillian** [comment]
@Rezessivo das Mapping der zwischen Template ID und Gerät steht in der [DeviceTemplates.xml](https://github.com/zivillian/ism7mqtt/blob/master/src/ism7mqtt/Resources/DeviceTemplates.xml), die Parameter findest du dann in der [ParameterTemplates.xml](https://github.com/zivillian/ism7mqtt/blob/master/src/ism7mqtt/Resources/ParameterTemplates.xml)

**Comment by Rezessivo** [comment]
@zivillian .... danke für die schnelle Antwort....die ParameterTemplates.xml ist leider leer :-(

**Comment by zivillian** [comment]
ne, die ist nur zu groß um die im Browser anzuzeigen - [der Link](https://raw.githubusercontent.com/zivillian/ism7mqtt/master/src/ism7mqtt/Resources/ParameterTemplates.xml) sollte die direkt anzeigen.

**Comment by ottelo9** [comment]
> ```json
> 180154
> ```

Jepp das war es. Die Kesselsolltemperatur wird nun angezeigt. Ich brauch nicht alle Parameter, d.h. ich muss jetzt in die [ParameterTemplates.xml](https://github.com/zivillian/ism7mqtt/blob/master/src/ism7mqtt/Resources/ParameterTemplates.xml) gehen und mir meine wichtigen Parameter rausfummeln, damit ich unter 100 komme?

**Comment by wartungsmonteur** [comment]
Hallo

Also sind es zu viele Parameter,  bei mir die Therme, drei Mischermodule und ein Solarmodul mit einer Zweifflächenanlage, also fast das Ausbaumaximum.

Was genau muss nun bearbeitet werden in welcher Datei um da die Anzahl zu verringern ? Eventuell geht das ja auch eleganter über eine Änderung des Addon, das Abfrageintervall verlängern oder immer nur Teile bestimmte Module abfragen. Vielen Dank und Grüße

**Comment by b3nn0** [comment]
> @zivillian
> 
> > Kannst du einmal testen was passiert, wenn du bei dem CGB-2 Gerät alle Parameter außer der Kesselsolltemperatur entfernst?
> 
> Jepp das war es. Die Kesselsolltemperatur wird nun angezeigt. Ich brauch nicht alle Parameter, d.h. ich muss jetzt in die [ParameterTemplates.xml](https://github.com/zivillian/ism7mqtt/blob/master/src/ism7mqtt/Resources/ParameterTemplates.xml) gehen und mir meine wichtigen Parameter rausfummeln, damit ich unter 100 komme?

Vermutlich einfacher, so habe ich es gemacht:
Die Parameters.json Datei nochmal löschen und Addon neu starten. Dann wird diese neu erzeugt mit allen verfügbaren Parametern.
Anschließend mal in HA die Entity-details für nicht benötigte Dinge angucken, dort findest du die entity_id. Diese beinhaltet die Nummern die zur Parameterdatei passen. Alles nicht benötigte dann aus der Parameterdatei raus löschen. Entweder ein ganzes device, oder eben nur einzelne Parameter. Beide IDs siehst du in der Entity ID:
![image](https://github.com/zivillian/ism7mqtt/assets/1858945/c9c685d7-cdcd-40cd-a906-1d7eb61a8a7e)


Etwas unschön: In der aktuellen Version bleiben die Entities in HA vorhanden, bis man manuell die discovery topics löscht.
Das wird sich mit der nächsten Version ändern - dann verschwinden die ganzen Entities die nicht in der Parameters.json datei gelistet sind automatisch.

**Comment by b3nn0** [comment]
Oh, auch denkbar: ihr könntet Mal probieren das Aktualisierungsintervall im Addon etwas hoch zu stellen, also 2-3 Minuten oder so. Vielleicht hilft das auch schon?

**Comment by ottelo9** [comment]
Danke für den Tipp mit der Parameter ID. So werde ich es machen. Nur was ich brauche kommt in die Liste. Wie kann ich denn die Discovery Topics löschen? Über den MQTT Explorer?

sonst warte ich auf die neue Version. Trotzdem schonmal danke für die Hilfe !!

**Comment by b3nn0** [comment]
Ja, z.B. über den MQTT explorer.. homeassistant/binary_sensor/.../config usw.
Aber ich persönlich würde einfach warten, ist etwas lästig das manuell zu machen.
Wann eine neue Version kommt kann ich allerdings nicht sagen - Ich aktualisiere das Addon sobald @zivillian  eine neue version tagt.

Wär übrigens cool wenn du trotzdem mal probieren könntest ob die Werte kommen wenn du einfach nur das Aktualisierungsintervall verlangsamst. Ich bin neugierig.. und für die Doku.

**Comment by ottelo9** [comment]
Habe wieder alles drin, Addon wieder gestartet. Die Kesselsolltemperatur aktualisiert sich nicht mehr. Mir ist aufgefallen, dass andere Werte auch sehr selten aktualisiert werden. Manche vor 3h oder noch länger.

Hier im Log sieht man, dass immer nur ein paar Werte rein kommen. Oder ist das normal? Ruft das Addon immer ALLE Daten ab und parst dann das zurück bekommene Paket?
https://pastebin.com/vGxJ3zWh

**Comment by b3nn0** [comment]
Nein, du bekommst nur Änderungen wenn sich auch tatsächlich was ändert. Am besten kann man das mit so Parametern sehen die sich sehr viel ändern (Vorlauftemperatur oder sowas). Du würdest die Änderung also nur sehen wenn sich die Kesselsolltemperatur auch wirklich ändert (tut sie das? Vermutlich nur bei Schwankungen der gemittelten Außentemperatur?)

**Comment by wartungsmonteur** [comment]
Hallo

Ich habe den Eindruck dass das Addon zu kurz die Werte abfragt. Bei miir sind es fast 400 Werte bei der Heizungsanlage. Den Abfrageintervall habe ich auf 300 sek hoch genommen ohne Erfolg. Die kleinere zweite Anlage, Wärmepumpe) mit der identischen Hardware (ism7 FW 2.1) liefert ohne Probleme alle Daten korrekt.

**Comment by b3nn0** [comment]
Gut, dann ist das auch eine Erkenntnis: Das ISM7 ist mit so vielen Parametern überfordert, ungeachtet des Update-Intervalls. Es hilft also wirklich nur, dass man einige nicht genutzte Parameter aus der JSON Datei entfernt.

**Comment by ottelo9** [comment]
Also ich hab alles unwichtige aus der JSON entfernt. Nun läuft es bei mir gut.

> Du würdest die Änderung also nur sehen wenn sich die Kesselsolltemperatur auch wirklich ändert (tut sie das?
Jepp, ich habe extra die Tagtemperatur auf 30°C gestellt, damit die Heizung anspringt. Habe es vergessen wieder runterzustellen, lief bis eben ^^^schön warm nun.

**Comment by wartungsmonteur** [comment]
Hallo

Nachdem ich zwei Mischermodule vom Wolf Bussystem entfernert hatte und die .json neu erzeugt habe, läuft nun alles perfekt.

**Comment by wartungsmonteur** [comment]
Hallo

Hier meine .json mit den wichtigsten Werten, Gerät eine CGB 2-14, 3xMischermodule (nur ein Modul wird ausgelesen an dem die Rücklaufanhebung hängt) und ein SM2 Solarmodul mit einer Zweikreisanlage, funktioniert super. Als Hub habe ich noch eine CHA7 Wärmepumpe mit allen Parametern am laufen.

{
  "Devices": [
    {
      "ReadBusAddress": "0x35",
      "WriteBusAddress": "0x30",
      "DeviceTemplateId": 220000,
      "Parameter": [
        220042,
        220103,
        320042,
        320043,
        320044,
        320045,
        320046,
        320047,
        320048,
        320049,
        320050,
        320051,
        320052,
        320053,
        320054,
        320055,
        320056,
        320057,
        320058,
        320059,
        320060,
        320061,
        320062,
        330000,
        330001,
        330002,
        330003,
        330004,
        330005,
        330006,
        330007,
        330008,
        330009,
        330010,
        330011
      ]
    },
    {
      "ReadBusAddress": "0x35",
      "WriteBusAddress": "0x30",
      "DeviceTemplateId": 350000,
      "Parameter": [
        320021,
        320022,
        320023,
        320024,
        320025,
        320026,
        320027,
        320028,
        320029,
        320030,
        320031,
        320032,
        320033,
        320034,
        320035,
        320036,
        320037,
        320038,
        320039,
        320040,
        320041,
        350001,
        350004,
        350011,
        350013,
        350016
      ]
    },
    {
      "ReadBusAddress": "0x52",
      "WriteBusAddress": "0x52",
      "DeviceTemplateId": 40000,
      "Parameter": [
        40003,
        40024,
        40026
      ]
    },
    {
      "ReadBusAddress": "0x76",
      "WriteBusAddress": "0x71",
      "DeviceTemplateId": 70000,
      "Parameter": [
        70000,
        70020,
        70027,
        70089,
        70090,
        70150
      ]
    },
    {
      "ReadBusAddress": "0x8",
      "WriteBusAddress": "0x3",
      "DeviceTemplateId": 180000,
      "Parameter": [
        180012,
        180143,
        180148,
        180154
      ]
    },
    {
      "ReadBusAddress": "0x85",
      "WriteBusAddress": "0x85",
      "DeviceTemplateId": 260000,
      "Parameter": [
        260001,
        320105,
        320106,
        320107,
        320108,
        320109,
        320110,
        320111,
        320112,
        320113,
        320114,
        320115,
        320116,
        320117,
        320118,
        320119,
        320120,
        320121,
        320122,
        320123,
        320124,
        320125
      ]
    },
    {
      "ReadBusAddress": "0x86",
      "WriteBusAddress": "0x86",
      "DeviceTemplateId": 360000,
      "Parameter": [
        320126,
        320127,
        320128,
        320129,
        320130,
        320131,
        320132,
        320133,
        320134,
        320135,
        320136,
        320137,
        320138,
        320139,
        320140,
        320141,
        320142,
        320143,
        320144,
        320145,
        320146,
        360000,
        360001,
        360004,
        360005,
        360006,
        360007,
        360008,
        360010,
        360011,
        360012,
        360013,
        360014,
        360015,
        360016,
        360050,
        360065,
        360066,
        360086,
        360093,
        360110,
        360124,
        360130,
        360132,
        360136,
        360145,
        360147,
        360148,
        360149,
        360150
      ]
    }
  ]
}

**Comment by Rezessivo** [comment]
wenn hier irgendjemand zufällig nen Cob-20 Öl-Brennwertkessel im Einsatz hat, würde ich meinen linken Arm für die ism7-wolf-parameters.json geben ;) - ich habe das Gefühl dass bei der automatischen (ersten) Abfrage die .json die falschen Werte übertragen bekommt vom ism7?!?!? Habe die device und Parameters Template durchgeackert, aber meinen Warmwasserspeicherwert erst gar nicht gefunden.....Habe dabei bemerkt dass es in der devices.template auch "cob-2" gibt. Dort gibt es auch einen Warmwasserwert (der mir auch im ism7 direkt) angezeigt wird. (bei mir wurde in der config "cob" angelegt..... würde es mir vielleicht selber hinbiegen können, wenn ich wüsste auf welcher Busadresse ich den cob-2 konfigurieren müsste....

**Comment by wartungsmonteur** [comment]
Guten Morgen 

In der .json sind einige falsche Namen und auch viele falsche Adressen ohne Ziel hinterlegt. 

Eventuell findet man die richtige Zuordnung im Update File des BM2 Modules. Dieses bei Wolf herunterladen, entpacken und nachschauen. Normalerweise sind die wichtigsten Parameter bei allen Geräten gleich. Beim COB sind nur einige technische Parameter anders wegen der Ölansteuerung, Gebläsedrehzahl, Magnetventil für  die 2 Stufen. Solltest du da fündig werden bitte mitteilen,  ich suche da auch noch paar Parameter für  die Gasgeräte und Wärmepumpe.

**Comment by lefgrter** [comment]
> @RezessivoThe mapping between the template ID and the device is in the [DeviceTemplates.xml](https://github.com/zivillian/ism7mqtt/blob/master/src/ism7mqtt/Resources/DeviceTemplates.xml) , you can then find the parameters in the [ParameterTemplates.xml](https://github.com/zivillian/ism7mqtt/blob/master/src/ism7mqtt/Resources/ParameterTemplates.xml)

Is there any way to have the entities translated in English in my home assistant server?

**Comment by lefgrter** [comment]
Unfortunately the Wolf link module is a Joke. Pro is a bit better in handling data form bigger systems. My system has now 540 entities and soon it will have more that 700. It was impossible for me to even create the parameter.Json file. As it timed out at 2 minutes before creating the file. I disables 3 mixer modules so from 15 bus devices reduced size of the system to 12 and I managed to create the file. After that I manually added the 3 missing mixer modules and now it is working. Next step is to erase the entities that aren't important for the operation of the system
